export { default as HomePage } from './home-page'
export { default as TutorialsPage } from './tutorials-page'
export { default as NotFoundPage } from './not-found-page'
export { default as TeachersPage } from './teachers-page'
export { default as SamplesPage } from './samples-page'